highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
#permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: https://dmonagha.github.io/cv
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /cv/
title: Derek Monaghan's Resume
name: Derek Monaghan
email: derek@sysadmin.fail
email_full: mailto:derek@sysadmin.fail
website: sysadmin.fail
website_full: https://sysadmin.fail/
github: dmonagha
twitter: derek_monaghan

# needed for travis-ci build
exclude: [vendor]
